### ISSUE TITLE
Incorrect Balance Displayed on second machine

### ISSUE THREAD

**Issue by pot8oe** [mobilecoinofficial/mobilecoin#100]
MobileCoin client displayed the incorrect balance upon start when run on a second machine. The correct balance was displayed after subsequent check balance requests and client restarts.

**Steps to reproduce**

1. Extract & Run Linux client on one machine.

1. Make a payment

1. Extract & Run Linux client on a second machine.

1. Client displayed original balance of 100.000MOB

1. Check Balance then displayed correct balance of 98.999MOB

**Comment by eranrund** [comment]
The balance is a reflection of the current state of the local ledger. When `mobilecoind` starts, it syncs the ledger from the network - but that process takes some time, so if the balance is checked before the ledger has finished syncing, you would experience this issue.

A fix is coming to the test client that would make it block until the ledger has fully synced before performing the initial balance check.
