### ISSUE TITLE
[feature request]save processed blocks into database, and expose an api

### ISSUE THREAD

**Issue by Ljzn** [mobilecoinofficial/mobilecoin#190]
Hi, mobilecoin team. 

I'm working in a cryptocurrency exchange, we are planning to launch mobilecoin on our site. Your works on protecting user's privacy are awesome.

The major job of our exchange program is to monitor user's deposit. We use `get_block` API to fetch the block data and filter the transaction data we need, for coins like BTC, LTC, etc.. But mobilecoind's `get_block` API only returning the encrypted content.

Currently, mobilecoind will process blocks via this function https://github.com/mobilecoinofficial/mobilecoin/blob/30bffcb62aecb422f0d3086e23c5d00e6e816e5b/mobilecoind/src/sync.rs#L314 . Would you like to save the processed data into a database, then expose an API like `get_block_with_decrypted_data` for fetching the keyimages and utxos related to our user's addresses.

Without this API, we have to decrypt the block data by ourselves, it's a bit inconvenient.

Thank you!

**Comment by bradymob** [comment]
Hi! Thanks for your interest in integrating us. Please tell us more about your organization in the form below and we’ll follow-up quickly. https://docs.google.com/forms/d/e/1FAIpQLSeuahcxiK-HE21SMMjjpLL0nUU5ujqcLtHvWfbSKCJ0kFjfyg/viewform

**Comment by Ljzn** [comment]
> Hi! Thanks for your interest in integrating us. Please tell us more about your organization in the form below and we’ll follow-up quickly. https://docs.google.com/forms/d/e/1FAIpQLSeuahcxiK-HE21SMMjjpLL0nUU5ujqcLtHvWfbSKCJ0kFjfyg/viewform

Submitted.

**Comment by bradymob** [comment]
Hi - I'm really sorry, but I can't find you in there. Probably a lot easier for you to mail me at support {at} mobilecoin.com.

**Comment by eranrund** [comment]
I believe this has been addressed by https://github.com/mobilecoinofficial/mobilecoin/blob/master/mobilecoind/api/proto/mobilecoind_api.proto#L49

**Comment by Ljzn** [comment]
> I believe this has been addressed by https://github.com/mobilecoinofficial/mobilecoin/blob/master/mobilecoind/api/proto/mobilecoind_api.proto#L49

Awesome! I will give a try.
