### ISSUE TITLE
The API routers of mobilecoind-mirror

### ISSUE THREAD

**Issue by Ljzn** [mobilecoinofficial/mobilecoin#451]
Hi,

I installed and ran the latest release. According to the README of mobilecoind-mirror, I can access /block/{n} and /processed-block/{n}. I tried some other routes, but I can't access them. What other routes does mobilecoind-mirror support? For example, I want to use it to sign and send transactions.

**Comment by sugargoat** [comment]
Hi @Ljzn,

I believe you are looking for the `mobilecoind-json` tool, which supports creating and sending transactions, as well as checking balance and managing your wallet. `mobilecoind-mirror` is a fairly specific API, meant to run in conjunction with `mobilecoind-json`, to provide "public" access (without any private keys) to a pre-processed ledger (at the `ProcessedBlock` API). `mobilecoind-json`, on the other hand, is a straight HTTP REST wrapper of the mobilecoind API.

Relevant links:

* [mobilecoind-json](https://github.com/mobilecoinofficial/mobilecoin/tree/master/mobilecoind-json)
* [mobilecoind proto](https://github.com/mobilecoinofficial/mobilecoin/blob/master/mobilecoind/api/proto/mobilecoind_api.proto) (the mobilecoind API)
* [python client that wraps the mobilecoind API](https://github.com/mobilecoinofficial/mobilecoin/blob/master/mobilecoind/clients/python/lib/mobilecoin/__init__.py)
* [java client that wraps the mobilecoind API
](https://github.com/mobilecoinofficial/mobilecoin/blob/master/mobilecoind/clients/java/mob_client/src/main/java/com/mobilecoin/mob_client/App.java)

Let us know if this provides the API you are looking for!

We provide

**Comment by Ljzn** [comment]
Thanks, will try.
