### ISSUE TITLE
Build fails on Ubuntu 18.04.3 LTS (Elementary OS 5.1) with kind: NotFound, error: "failed to spawn \"protoc\" \"protoc\" \"--version\": No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by mad-de** [mobilecoinofficial/mobilecoin#6]
> madde@madde-laptop:~/Documents/Programmierung/rust/mobilecoin$ cargo build
> [...]
> error: failed to run custom build command for `attest-api v0.1.0 (/home/madde/Documents/Programmierung/rust/mobilecoin/attest/api)`
> 
> Caused by:
>   process didn't exit successfully: `/home/madde/Documents/Programmierung/rust/mobilecoin/target/debug/build/attest-api-58fb4ed0281a428b/build-script-build` (exit code: 101)
> --- stdout
> cargo:rerun-if-changed=./proto
> cargo:rerun-if-changed=./proto/attest.proto
> 
> --- stderr
> thread 'main' panicked at 'Failed to compile gRPC definitions!: Custom { kind: NotFound, error: "failed to spawn `\"protoc\" \"protoc\" \"--version\"`: No such file or directory (os error 2)" }
> 
> failed to find `protoc`, `protoc` must be availabe in `PATH`', src/libcore/result.rs:1188:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: build failed

Running ./mob prompt
> madde@madde-laptop:~/Documents/Programmierung/rust/mobilecoin$ ./mob prompt
> Warning: Could not pull from:  gcr.io/mobilenode-211420/builder-install:1_9
> Warning: Could not pull from:  gcr.io/mobilenode-211420/builder-install:1_8
> Traceback (most recent call last):
>   File "./mob", line 272, in <module>
>     if args.action == "image" or not have_tag(tag):
>   File "./mob", line 149, in have_tag
>     return len(subprocess.check_output(cmd)) > 0
>   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 423, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'

System:
Elementary OS 5.1 (Built on Ubuntu 18.04.3 LTS)

**Comment by AndreRenaud** [comment]
It looks like you're missing the protobuf compiler and docker packages - does running `apt-get install protobuf-compiler protobuf-c-compiler docker` resolve the issue?

**Comment by joekottke** [comment]
Awesome! Thanks for reporting back.  In most Linux environments, you can add yourself to the `docker` group, with something like `sudo adduser <your-username> docker` or something similar.  That way you don't have to elevate to root privileges to run a command that in-turn executes docker commands.
