### ISSUE TITLE
Testnet client: Sending coins to own address

### ISSUE THREAD

**Issue by mad-de** [mobilecoinofficial/mobilecoin#68]
It's possible and there is no warning, when sending money to his own address. There's nothing in the source code (as of yet) to warn you, but I'd think that's behaviour that should be discouraged. It also shows a wrong remaining balance for that.

**Comment by sugargoat** [comment]
Hello!

It is possible to send mobilecoins to your own address, and in some cases that may be the desired outcome action, for example, if you are consolidating smaller amounts of change into a larger UTXO. This is a fairly advanced way to interact with the blockchain, so I think you are right that it is not intuitive in the client, and some client/wallet developers may choose to disallow this action.

The balance after sending to yourself should reflect the same balance you had previously, minus the fee amount for sending a transaction.

What was your balance before and after?

Thanks for helping us test TestNet!

**Comment by mad-de** [comment]
> Hello!
> 
> It is possible to send mobilecoins to your own address, and in some cases that may be the desired action, for example, if you are consolidating smaller amounts of change into a larger UTXO. This is a fairly advanced way to interact with the blockchain, so I think you are right that it is not intuitive in the testnet client, and some client/wallet developers may choose to disallow this action.
> 
> The balance after sending to yourself should reflect the same balance you had previously, minus the fee amount for sending a transaction.
> 
> What was your balance before and after?
> 
> Thanks for helping us test TestNet!

Ohh yeah I thought it was clear:

I have 1 Mob in my account. I send 0.5 Mob to myself. It displays:

> This is a payment request for 500000.000 µMOB.
> You will be charged a fee of 10 pMOB to send this payment. Your remaining
> balance after sending this payment will be 499999.999 µMOB.

**Comment by sugargoat** [comment]
> It doesn't "predict", where the money goes to here. But the client itself is fairly simple, so that's probably not a big issue. The final balance of course is correct.

That's right - the client would need to store more state (and be confident that the transaction will be confirmed to the ledger) to predict that the output will contribute to your final balance once the transaction is complete.

I'll close this issue - thank you again!
